# Generated by Django 4.0 on 2022-01-24 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_teacherstudent_alter_student_group_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='teacher',
            new_name='teachers',
        ),
    ]
